name: wallpapers
version: 4.2.1+5
publish_to: none
description: Free Wallpaper HD.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.3
  encrypt: ^5.0.1
  firebase_analytics: ^10.0.6
  firebase_core: ^2.4.0
  firebase_database: ^10.0.8
  flutter_cache_manager: ^3.3.0
  flutter_staggered_grid_view: ^0.6.2
  get: ^4.6.5
  google_fonts: ^3.0.1
  google_mobile_ads: ^2.2.0
  infinite_scroll_pagination: ^3.2.0
  startapp_sdk: ^0.4.1
  upgrader: ^6.5.0
  wallpaper_manager_flutter: ^0.0.2

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  change_app_package_name: ^1.1.0

flutter: 
  uses-material-design: true

