name: wallpapers
version: 4.0.0+5
publish_to: none
description: Free Wallpaper HD.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  cached_network_image: ^3.2.3
  dio: ^5.3.2
  encrypt: ^5.0.3
  firebase_analytics: ^10.0.6
  firebase_core: ^2.4.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_staggered_grid_view: ^0.7.0
  get: ^4.6.5
  google_fonts: ^6.1.0
  google_mobile_ads: ^3.1.0
  image_gallery_saver: ^2.0.3
  infinite_scroll_pagination: ^4.0.0
  path_provider: ^2.1.0
  permission_handler: ^11.0.1
  share_plus: ^7.1.0
  startapp_sdk: ^0.4.1
  upgrader: ^8.2.0
  wallpaper_manager_flutter: ^0.0.2

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter
  change_app_package_name: ^1.1.0

flutter: 
  uses-material-design: true

